export const FETCH_DETAILS = "shows/FETCH_DETAILS";
export const FETCH_DETAILS_COMPLETED = "shows/FETCH_DETAILS_COMPLETED";
export const FETCH_DETAILS_FAILED = "shows/FETCH_DETAILS_FAILED";

export const FETCH_LIST = "shows/FETCH_LIST";
export const FETCH_LIST_COMPLETED = "shows/FETCH_LIST_COMPLETED";
export const FETCH_LIST_FAILED = "shows/FETCH_LIST_FAILED";
